# Generated by Django 4.2.1 on 2023-06-04 02:03

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('types', models.CharField(choices=[('VID', 'Video'), ('AUD', 'Audio'), ('COD', 'Plain text'), ('IMA', 'Image'), ('DOC', 'Documents')], max_length=4, verbose_name='types of file')),
                ('allow_formats', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
