# Generated by Django 4.2.1 on 2023-06-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_explorer', '0002_alter_typefile_types_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url_file',
            field=models.URLField(null=True, verbose_name='File URL'),
        ),
    ]
