# Generated by Django 4.2.1 on 2023-06-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_explorer', '0005_alter_file_folder_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url_file',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='File URL'),
        ),
    ]
