# Generated by Django 4.2.1 on 2023-06-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_explorer', '0006_alter_file_url_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size_mb',
            field=models.FloatField(blank=True, verbose_name='Size MB'),
        ),
    ]
